apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-local-data-pv
  namespace: homelab
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kavita-local-data-storage
  local:
    path: /path/to/dir
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node
