apiVersion: v1
kind: PersistentVolume
metadata:
  name: hedgedoc-local-data-pv
  namespace: homelab
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hedgedoc-local-storage
  local:
    path: /path/to/dir
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - Node
