apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-local-data-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hedgedoc-local-storage
  volumeName: hedgedoc-local-data-pv
