apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-postgres
  namespace: homelab
  labels:
    name: mealie-postgres
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: mealie-postgres
  template:
    metadata:
      labels:
        name: mealie-postgres
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: mealie-postgres #
          image: "postgres:15" # 
          env:
            - name: POSTGRES_PASSWORD
              value: mealie
            - name: POSTGRES_USER
              value: mealie
            - name: PGUSER
              value: mealie
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mealie-postgres-local-data-pvc
