apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-postgres-local-data-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mealie-postgres-local-storage
  volumeName: mealie-postgres-local-data-pv
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-local-data-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mealie-local-storage
  volumeName: mealie-local-data-pv
  resources:
    requests:
      storage: 2Gi
