apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-all-ingress"
spec:
  endpointSelector:
    matchLabels:
      ingress: all
  ingress:
    - fromEntities:
      - world
