apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy-local-cache-pv
  namespace: homelab
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ntfy-local-storage
  local:
    path: /Your/absolute/cache/path/here
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - Node
