apiVersion: v1
kind: Service
metadata:
  name: ntfy-svc
  namespace: homelab
  labels:
    name: ntfy-svc
  annotations:
    name: ntfy-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: http
      protocol: TCP
      nodePort: 30001
  selector:
    name: ntfy
