apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: homelab
  labels:
    name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak
  template:
    metadata:
      labels:
        name: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.4
          args: ["start-dev"]
          envFrom:
          - configMapRef:
              name: keycloak-configmap
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /data/log/
              name: log
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: keycloak-db-pvc
