apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
  namespace: homelab
  labels:
    name: keycloak-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-postgres
  template:
    metadata:
      labels:
        name: keycloak-postgres
    spec:
      containers:
        - name: keycloak-postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: test123
            - name: POSTGRES_DB
              value: keycloak
          resources:
            limits:
              memory: "100Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: keycloak-postgres-pvc
