apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db-pv
  namespace: homelab
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: keycloak-local-storage
  local:
    path: /path/for/keycloak
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-db-pv
  namespace: homelab
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: keycloak-postgres-local-storage
  local:
    path: /path/for/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node