apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  namespace: homelab
  labels:
    name: keycloak-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    name: keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-svc
  namespace: homelab
  labels:
    name: keycloak-postgres-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      # nodePort: 30001
  selector:
    name: keycloak-postgres

