apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homelab
  labels:
    name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: homepage
  template:
    metadata:
      labels:
        name: homepage
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: homepage # https://github.com/gethomepage/homepage
          image: "ghcr.io/gethomepage/homepage:v1.0.4" # Latest release as of 19-03-2025
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS # Required ENV now for releases over v1.0.0
              value: "*" # Allow all hosts (will be limited by NW policy so we good)
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            # runAsUser: 1000
            # runAsGroup: 1000
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-local-pvc
        # - name: logs
        #   emptyDir: {}
