apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: default
namespace: homelab
resources:
  - diun-configmap.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - allow_kubeapi_ingress_egress_diun.yaml
