apiVersion: v1
kind: PersistentVolume
metadata:
  name: diun-local-data-pv
  # namespace: default
  namespace: homelab
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: diun-local-data-storage
  local:
    path: /path/to/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node
