apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - service.yaml
  - pv.yaml
  - pvc.yaml
  - outline-configmap.yaml
  - redis-dep.yaml
  - postgres-dep.yaml
  - outline-dep.yaml
