apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
  namespace: homelab
  labels:
    name: outline
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: outline
  template:
    metadata:
      labels:
        name: outline
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: outline
          image: "docker.getoutline.com/outlinewiki/outline:0.82.0"
          envFrom:
          - configMapRef:
              name: outline-configmap
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "yarn db:migrate --env production-ssl-disabled && yarn start"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/outline/data
              name: data
          securityContext:
            allowPrivilegeEscalation: false
            # runAsUser: 1000
            # runAsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: outline-local-config-pvc

