apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-local-config-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: outline-storage
  volumeName: outline-local-config-pv
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-postgres-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: outline-postgres-storage
  volumeName: outline-postgres-pv
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-redis-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: outline-redis-storage
  volumeName: outline-redis-pv
  resources:
    requests:
      storage: 20Gi