apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline-redis
  namespace: homelab
  labels:
    name: outline-redis
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: outline-redis
  template:
    metadata:
      labels:
        name: outline-redis
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: outline-redis
          image: "redis"
          envFrom:
          - configMapRef:
              name: outline-configmap
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          imagePullPolicy: IfNotPresent
          command: ["redis-server", "/redis.conf"]
          ports:
            - name: http
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /redis.conf
              name: config
          securityContext:
            allowPrivilegeEscalation: false
            # runAsUser: 1000
            # runAsGroup: 1000
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: outline-redis-pvc

