apiVersion: v1
kind: PersistentVolume
metadata:
  name: stirlingpdf-local-data-pv
  namespace: homelab
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: stirlingpdf-local-storage
  local:
    path: 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODE

