apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - pv.yaml
  - pvc.yaml
  - service.yaml
  - convertx-env-configmap.yaml
#  - ingress.yaml
  - deployment.yaml
