apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-fixed-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:

    processors:
      batch:

    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: pyroscope-fixed-service:4040
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        profiles:
          receivers: [otlp]
          exporters: [otlp]
      
      telemetry:
        logs:
          level: debug
