apiVersion: v1
kind: Service
metadata:
  name: otel-collector-fixed-service
spec:
  selector:
    app: otel-collector-fixed
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
